### ISSUE TITLE
Suitable for large stores?

### ISSUE THREAD

**Issue by dcworldwide** [jviotti/electron-json-storage#17]
Are there any store size limitations imposed by this library?

**Comment by jviotti** [comment]
Hi @dcworldwide ,

Thanks for reaching out. There are no hard size limitations imposed by this library nor by JSON (the mechanism this library uses to store information), however I believe various web browsers can only handle JSON objects of about ~40 MB (which bites Electron's renderer view).

My suggestion is to to create various stores for certain prefixes, as a way to avoid having a single monolithic store, or too many little stores, which would cause a lot of I/O.

Let me know how it goes!

**Comment by dcworldwide** [comment]
Thanks @jviotti for the great feedback. I'll let you know my findings if we run with this lib :)
