### ISSUE TITLE
Ability to override file location

### ISSUE THREAD

**Issue by jayalfredprufrock** [jviotti/electron-json-storage#19]
Would you be open to a pull request that provides the ability to override the path where files are stored? I'm aware that you can use app.setPath('userData', 'newPath') to change the default userData path, but this can be inconvenient in certain cases (i.e. when you simply want to place the file in a subfolder).

**Comment by jviotti** [comment]
Hey there!

Thanks for reaching out. I'm definitely open for that :) 

On Wed, Aug 24, 2016 at 01:41:06PM -0700, Andrew Smiley wrote:
> Would you be open to a pull request that provides the ability to override the path where files are stored? I'm aware that you can use app.setPath('userData', 'newPath') to change the default userData path, but this can be inconvenient in certain cases (i.e. when you simply want to place the file in a subfolder). 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/jviotti/electron-json-storage/issues/19

-- 
Juan Cruz Viotti
Software Engineer

**Comment by jayalfredprufrock** [comment]
Great, I'm thinking two changes:

1. Provide functions `setDefaultPath` and `getDefaultPath`.
2. Allow keys to contain a relative path, to be appended to the default path. So `storage.set("path/to/data", {})` would set "data.json" at "defaultPath/path/to"

If you don't mind an extra dependency, we could use mkdirp to make sure directories are created automatically if they don't already exist.

Thoughts?

**Comment by jviotti** [comment]
Hi @jayalfredprufrock 

> Provide functions `setDefaultPath` and `getDefaultPath`.

Sounds good. I don't like the "default" word here very much, since it somehow implies that the user can override the base path at runtime at the moment of saving or retrieving a value. Maybe `setBasePath`/`getBasePath`?

> Allow keys to contain a relative path, to be appended to the default path. So `storage.set("path/to/data", {})` would set "data.json" at "defaultPath/path/to"

This is an interesting idea. What's your use case for it? More organisation of the settings directory?

> If you don't mind an extra dependency, we could use mkdirp to make sure directories are created automatically if they don't already exist.

Sure, go for it :)

If you don't mind, can we handle this one in a separate PR, so we can focus on each change one at a time?

**Comment by jayalfredprufrock** [comment]
Totally agree, `setBasePath` / `getBasePath` is less confusing and more appropriate.

Regarding the relative path feature, my use case is for handling per-user settings. My application requires logging into an account and since multiple users could be using separate accounts on the same computer/user, it's convenient to store all user related data in a uniquely identified sub folder for easy retrieval and cleanup. 

I'm happy to prepare separate pull requests and tests, especially since implementing the relative paths idea will be a bit trickier. Look for that over the next few days. Thanks!

**Comment by jviotti** [comment]
Sounds very exciting! Let me know if I can help with anything along the
way, and thanks a lot for the contribution :)

On Thu, Aug 25, 2016 at 09:32:04AM -0700, Andrew Smiley wrote:
> Totally agree, `setBasePath` / `getBasePath` is less confusing and more appropriate.
> 
> Regarding the relative path feature, my use case is for handling per-user settings. My application requires logging into an account and since multiple users could be using separate accounts on the same computer/user, it's convenient to store all user related data in a uniquely identified sub folder for easy retrieval and cleanup. 
> 
> I'm happy to prepare separate pull requests and tests, especially since implementing the relative paths idea will be a bit trickier. Look for that over the next few days. Thanks!
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/jviotti/electron-json-storage/issues/19#issuecomment-242453506

-- 
Juan Cruz Viotti
Software Engineer

**Comment by jviotti** [comment]
Check v3.0.0. This new version stores settings inside a `storage/` subdirectory of `userPath`. Keep in mind this is a breaking change, so you might need to include code in your application to transfer old settings to the new location.

**Comment by remyvanlerberghe** [comment]
Are you still open to a PR that implements the ability of setting the location of the file ?

**Comment by jviotti** [comment]
@remyvanlerberghe Totally!
