### ISSUE TITLE
Consider merging with https://github.com/ran-y/electron-storage

### ISSUE THREAD

**Issue by khullah** [jviotti/electron-json-storage#20]
https://github.com/ran-y/electron-storage is able to use inner folders when saving data - this way, you could have several electron apps in a computer, each using the same filenames (like 'settings.json') in each folder.

Both are great projects, though similar!

**Comment by jviotti** [comment]
Hi @khullah ,

Thanks a lot for the suggestion! I don't see a reason why both project can't co-habitate, despite similar. This modules is also getting inner folders support, as discussed in https://github.com/jviotti/electron-json-storage/issues/19.

**Comment by khullah** [comment]
Yes, thats right! Not the initial request, but [this comment](https://github.com/jviotti/electron-json-storage/issues/19#issuecomment-242219520) points it out - I was thinking exactly in the second item. And that other project also uses mkdirp.

**Comment by jviotti** [comment]
I'm closing this issue, please re-open if you have any other suggestions!
