### ISSUE TITLE
Unsure where to insert the set function

### ISSUE THREAD

**Issue by ohalligan** [jviotti/electron-json-storage#21]
I want to store a list variable called notebookList {notebookOne,notebookTwo,notebookThree}

How do I modify this code:

```
const storage = require('electron-json-storage');

storage.set('foobar', { foo: 'bar' }, function(error) {
  if (error) throw error;
});
```

Also, do I insert it anywhere in the index.html file?

**Comment by jviotti** [comment]
Hi @ohalligan ,

> I want to store a list variable called notebookList {notebookOne,notebookTwo,notebookThree}
> How do I modify this code:

I'm not sure I understand the question. Should an array of object suffice?

```
storage.set('mydata', {
  notebooks: [
    {
      name: 'notebookOne'
    },
    {
      name: 'notebookOne'
    },
    {
      name: 'notebookOne'
    }
  ]
}, function(error) {
  if (error) throw error;
});
```

> Also, do I insert it anywhere in the index.html file?

You can call the functions from anywhere in the renderer process!

**Comment by jviotti** [comment]
I'm going to close this as resolved. Please re-open if you have any other questions!
