### ISSUE TITLE
Storage.get with array of keys

### ISSUE THREAD

**Issue by ArsNV** [jviotti/electron-json-storage#25]
Can you add to storage.get new features
array of keys (to get multiply jsons at once)
null(to get all storage)

**Comment by jviotti** [comment]
Sounds good! I'll going on vacations tomorrow, but I'll try to get on it in between. For now, you could use an async flow utility like http://caolan.github.io/async/docs.html in your application!

**Comment by ArsNV** [comment]
Thanks

**Comment by jviotti** [comment]
Thanks for the ping. I've implemented `.getAll()` and will implement support for an array of keys in `.get()`.

**Comment by jviotti** [comment]
I've implemented `.getMany()` here: https://github.com/jviotti/electron-json-storage/pull/35

**Comment by jviotti** [comment]
I've published v2.1.0 to npm with these changes.
