### ISSUE TITLE
Might delete unexpected files

### ISSUE THREAD

**Issue by anri-asaturov** [jviotti/electron-json-storage#28]
https://github.com/jviotti/electron-json-storage/blob/master/lib/storage.js#L227
This line is a potential disaster, it assumes only electron-json-storage can create json files in user data folder root. I suggest creating a subfolder.

**Comment by jviotti** [comment]
Hi @anri-asaturov,

I definitely agree! I'll get on this next week (I'm on vacations at the moment), but happy to take a PR if you need this sooner.

**Comment by jviotti** [comment]
Check v3.0.0. This new version stores settings inside a `storage/` subdirectory of `userPath`. Keep in mind this is a breaking change, so you might need to include code in your application to transfer old settings to the new location.
