### ISSUE TITLE
Promise support 

### ISSUE THREAD

**Issue by ndelvalle** [jviotti/electron-json-storage#30]
Are you considering promises support?

**Comment by jviotti** [comment]
Hi @ndelvalle ,

We used to have promises support built-in in earlier versions, which caused some issues when using the module in Electron's renderer process (see https://github.com/jviotti/electron-json-storage/issues/2).

The recommended way forward is to use something like [Bluebird's `.promisifyAll()`](http://bluebirdjs.com/docs/api/promise.promisifyall.html):

```js
const Promise = require('bluebird');
const storage = Promise.promisifyAll(require('electron-json-storage'));
```

And then using the functions with the `Async` suffix:

```js
storage.getAsync('foobar').then(function(data) {
  console.log(data);
});
```
