### ISSUE TITLE
storage.keys returns all contents from userDat

### ISSUE THREAD

**Issue by roldyclark** [jviotti/electron-json-storage#38]
I just want to populate a <select> element with the JSONs. Can't just filter out the file ext because it returns just the filename.

**Comment by jviotti** [comment]
> Can't just filter out the file ext because it returns just the filename.

Can you explain this in more detail? I don't think I clearly understand the issue. Maybe show an example?

**Comment by jviotti** [comment]
Check v3.0.0. This new version stores settings inside a `storage/` subdirectory of `userPath`. Keep in mind this is a breaking change, so you might need to include code in your application to transfer old settings to the new location.
