### ISSUE TITLE
wildcard character in key get

### ISSUE THREAD

**Issue by aj-ptw** [jviotti/electron-json-storage#39]
Hi i have been using a hierarchy in key naming and want to get all keys matching a prefix. I feel like this could be useful. Should I pr?

**Comment by jviotti** [comment]
Sounds good to me. Do you have any idea on how to expose this
functionality? I think we can extend `.get()` to support globs, so you
could do something like:

```js
storaget.get('prefix*', function(error, data) {
  console.log(data.prefixfoo);
  console.log(data.prefixbar);
  console.log(data.prefixbaz);
});
```

What do you think?

On Mon, Dec 12, 2016 at 09:38:37PM -0800, AJ Keller wrote:
> Hi i have been using a hierarchy in key naming and want to get all keys matching a prefix. I feel like this could be useful. Should I pr?
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/jviotti/electron-json-storage/issues/39

-- 
Juan Cruz Viotti
Software Engineer

**Comment by aj-ptw** [comment]
Yea i think globs is the most intuitive way to implement it. Especially with using `*` and `.get()`.

Another way you could do list all keys under a prefix so with `storage.list('foo/bar/')` and use an iterator or generator, i can't remember what it's called, but execute a function on each item.

**Comment by aj-ptw** [comment]
https://github.com/isaacs/node-glob

**Comment by jviotti** [comment]
You could do it with a generator, but that would require a huge refactoring of the module's internals. The easy way to do it from the side of your application would be to use `storage.keys()`, then filter the resulting keys to get the ones that match your prefix, and then use something like `async.map` to apply `storage.get` to each.

**Comment by jviotti** [comment]
I'm closing this since this feature can be done better and more generic from the client's code by res-using `.keys()` and `.get()`!
