### ISSUE TITLE
Don't return an error if storage/ does not exist.

### ISSUE THREAD

**Issue by stuartbrussell-intuit** [jviotti/electron-json-storage#46]
If the storage/ directory does not exist inside userData, then getAll() returns an error. The storage directory is completely private to electron-json-storage. If it doesn't exist, then please create it, or at least don't throw an error. Just return an empty object.

**Comment by stuartbrussell-intuit** [comment]
btw thank  you for implementing getAll().

**Comment by jviotti** [comment]
Hi @stuartbrussell-intuit ,

Thanks for reporting. I just sent a PR for this. Sorry for the huge delay, I've been unable to allocate time to this module recently :)

**Comment by jviotti** [comment]
Check v3.0.1!

**Comment by ablankenship10** [comment]
This should be optional functionality provided via an option on storage.get() call. I have default values to apply in the case of no previous saved data but its not possible to detect that there is no data now without either an error or a null value for the empty data.

**Comment by jviotti** [comment]
@ablankenship10 Maybe we can add a `hasDataDirectory()` function?
