### ISSUE TITLE
Can't use mainWindow.webContents.send() inside storage.get() callback

### ISSUE THREAD

**Issue by danjohnson95** [jviotti/electron-json-storage#47]
I'm getting some really strange behaviour here when I try to emit some data to the window once I've grabbed some data out of the storage.

I'm trying to send the stored data to the browser, but for brevity, here's a test scenario.

 ```javascript
const storage = require('electron-json-storage');
mainWindow = new BrowserWindow({width: 500, height: 500});

storage.get('config', function(err, config){
    // Emitting inside here won't get to the main window
    mainWindow.webContents.send('test', {foo: 'bar'});
});

// But emitting here *will* go through to the main window
mainWindow.webContents.send('test', {foo: 'bar'});
```

The `mainWindow.webContents.send()` function returns true regardless of whether it's run from inside the storage closure or anywhere else, however it only gets to the browser when called outside the `storage.get()` closure.

This problem only seems to be occurring inside callbacks that use this package.

**Comment by adamgoose** [comment]
Just for kicks, I'd be interested to know if the following works:

```js
const storage = require('electron-json-storage');
mainWindow = new BrowserWindow({width: 500, height: 500});

storage.get('config',(err, config) => { // <== Note the arrow function!
   // Emitting inside here won't get to the main window
   mainWindow.webContents.send('test', {foo: 'bar'});
});
```

**Comment by danjohnson95** [comment]
Unfortunately not 😞

**Comment by jviotti** [comment]
Hi @danjohnson95 ,

I'm only able to reproduce this when the event is emitted *before* the main window was completely up and running. Adding a long enough timeout around the `electron-json-storage` makes it work, so I guess you can find a way to wait until the main window has been loaded (and all its scripts executed) before loading the configuration, and then it should work.

I've tested with `electron-json-storage@3.0.1` and `electron@1.4.15`.

**Comment by danjohnson95** [comment]
Hi @jviotti 

My bad, and you were spot on! I was trying to send the event before the main window was finished loading.

I ended up sending an event from the client side to notify the main process when it's ready.

```javascript
// renderer.js (client side)
document.addEventListener('DOMContentLoaded', function(){
    ipcRenderer.send('get-data');
});

// main.js (main process)
ipcMain.on('get-data', function(e, msg){
    storage.get('config', function(err, config){
        mainWindow.webContents.send('test', config);
    });
});
````
Sorry about that, this is my first time working with Electron (and loving it so far).

Thanks for your help and also for this awesome package!

**Comment by jviotti** [comment]
Hey there,

Glad we got to the bottom of it! Have a great day!

On Thu, Feb 02, 2017 at 09:23:01AM -0800, Dan wrote:
> Hi @jviotti 
> 
> My bad, and you were spot on! I was trying to send the event before the main window was finished loading.
> 
> I ended up sending an event from the client side to notify the main process when it's ready.
> 
> ```javascript
> // renderer.js (client side)
> document.addEventListener('DOMContentLoaded', function(){
>     ipcRenderer.send('get-data');
> });
> 
> // main.js (main process)
> ipcMain.on('get-data', function(e, msg){
>     storage.get('config', function(err, config){
>         mainWindow.webContents.send('test', config);
>     });
> });
> ````
> Sorry about that, this is my first time working with Electron (and loving it so far).
> 
> Thanks for your help and also for this awesome package!
> 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/jviotti/electron-json-storage/issues/47#issuecomment-277022860

-- 
Juan Cruz Viotti
Software Engineer
