### ISSUE TITLE
Add a synchronous waitForDone()

### ISSUE THREAD

**Issue by stuartbrussell-intuit** [jviotti/electron-json-storage#49]
Our application sets storage values just before quitting. We need a way to make sure all the set operations are complete before we allow the app to proceed. The easiest way for us would be a synchronous call like waitForDone(). If there are no operations it just returns.

(Or, does electron-json-storage guarantee that state already exists before the app quits?)

**Comment by stuartbrussell-intuit** [comment]
Even an asynchronous waitForDone() would be better than not knowing.

**Comment by jviotti** [comment]
When the `.set()` callback is called its ensured that the data is written, however if you exit your application (with `process.exit()` or `app.quit()`) then the data might not be there.

This module can't block the application from being closed without being intrusive, however you can do this on your application by attaching a `onbeforeunload` event handler on the rendered process (http://electron.atom.io/docs/api/browser-window/#event-close) to prevent the application from being closed until the callback is called.
