### ISSUE TITLE
Does not work using remote

### ISSUE THREAD

**Issue by jseriff** [jviotti/electron-json-storage#5]
Two issues were found with this working as remote

First with promises:

See https://github.com/atom/electron/issues/3740

An application using this as remote will hang.  This can be resolved by removing the returns from the various exported methods, and using the callback.

Second, the app lookup in utils.js fails - the app needs to be retrieved from the electron remote instead of directly from electron.

**Comment by jviotti** [comment]
Hi @jseriff , thanks for the heads up.

> First with promises:
>
> See atom/electron#3740
>
> An application using this as remote will hang. This can be resolved by removing the returns from the various exported methods, and using the callback.

I can't seem to reproduce this. What electron version are running this module in (I'm testing in v0.36.4)? I'm working in app loading this module as remote with promises without any issues. Is there a chance you can build a gist, or share your app (if its open source) so I can test?

> Second, the app lookup in utils.js fails - the app needs to be retrieved from the electron remote instead of directly from electron.

I can reproduce this one by requiring the module without `remote`. I'll send a PR in a minute!

Thanks!

**Comment by jseriff** [comment]
I am using electron v36.7.  I will try to extract a minimal gist that reproduces the issue today.

**Comment by jviotti** [comment]
@jseriff Awesome, looking forward to that!

**Comment by jseriff** [comment]
I am unable to reproduce is a simple case.  I am going to dig into my particular case and see if there is some other interaction with my application that is causing the problem.  My application includes typescript, angular2, and es6 polyfills, so it may be an interaction with one of those things.

Closing for now - I will open a new ticket with this or another project if I am able to determine the root cause.

**Comment by jviotti** [comment]
I've published v1.1.0 to NPM which contains the fix for the electron app lookup.

**Comment by jseriff** [comment]
The root cause here appears to be an issue with BlueBird + ES6-Promise + Electron.  This library uses BlueBird on the browser side of electron.  When using remote, Electron maps these to objects on the renderer side - however if ES6-Promise (necessary for Angular2) is in place on the renderer side, it seems to get stuck in an infinite recursion when trying to cross the browser <-> renderer boundary.  When using either bluebird or es6-promise on both sides, the issue does not appear.

Unfortunately, I dont see a particularly clean fix for this - no particular code is a bad actor here, its just caused by the mess that is incompatible javascript promise implementations.  The possible fixes that I have identified:

1. Switch electron-json-storage to use es6-promise instead of bluebird (or actually use both - bluebird internally, and then return an es6-promise)
2. Allow electron-json-storage to operate on callbacks only
3. Switch angular2 to not require es6-promise (or more specifically, angular2-polyfills, which includes es6-promise)
4. Try to detect this case in electron remote and handle it

Options 3 and 4 seem unlikely.  Option 1 would help in my use case, but may cause issues in other cases.  

I am going to create a PR for option 2 - if a callback is provided, it is used and the promise is not returned at all.

**Comment by jviotti** [comment]
@jseriff Thanks for the research. I agree with option 2. Can you refactor the module to purely use callbacks and don't require Bluebird at all? I think we're better off without it, and if a user wants to use Bluebird, he can easily promisify the module and take care of the responsibility of possible incompatibilities.
