### ISSUE TITLE
issue with webpack and UglifyJs

### ISSUE THREAD

**Issue by vferko** [jviotti/electron-json-storage#53]
I am getting this error when trying to import the library in electron main process. Same with importing or requiring. Not sure what else I can do to help specifying the issue.

    ... gutil.PluginError('webpack', buildError)
    
    Error: electron/app/main.js from UglifyJs
    Unexpected token: name (args) [./~/cb2promise/index.js:7,0]

**Comment by jviotti** [comment]
This looks like a webpack/uglify issue rather than an issue with this module. Does the error still happen if you disable uglify?

**Comment by vferko** [comment]
Right. But shouldn't the promises be removed? Why it depends on cb2promise then?

**Comment by jviotti** [comment]
I got to the bottom of this issue, and solved it on 3.0.4. Check https://github.com/jviotti/electron-json-storage/issues/57
