### ISSUE TITLE
UglifyJs throws error: Unexpected token: name (args)

### ISSUE THREAD

**Issue by metachris** [jviotti/electron-json-storage#57]
I'm using `electron-json-storage` in an Electron app. It works when I run the local dev build with `npm run dev`, but as soon as I try make a production build, UglifyJs gives me the following error message for each time I import `electron-json-storage`:

```
ERROR in renderer.js from UglifyJs
Unexpected token: name (args)
```

**Comment by jviotti** [comment]
Hi @metachris ,

Thanks for reporting. I'm not sure what the issue could be. We have no variable name called `name`, so at least at first sight, it appears that the issue is coming from somewhere else.

Can you show me the contents of `renderer.js`? Also, could you share with me the compressed file? We could de-uglify and compare to the original source code to better understand what is it that UglifyJS is garbling.

**Comment by metachris** [comment]
Hi. Unfortunately, UglifyJS discards the renderer.js it reports the error in. Any idea how I can get it to preserve it?

**Comment by jviotti** [comment]
Not really sure. Can you point to a repository or a gist where I can reproduce the issue? I'm happy to give this a closer look!

**Comment by tvanro** [comment]
I'm having the same issue with electron-json-storage 3.0.1 and 3.0.2
electron-json-storage 3.0.0 works well with UglifyJS so it's a change that happened between 3.0.0 and 3.0.1.

**Comment by metachris** [comment]
Finally I got steps t reliably reproduce the error:

1. Start a new [electron-vue](https://github.com/SimulatedGREG/electron-vue) project
2. install the `electron-json-storage` dependency
3. require `electron-json-storage`
4. make a production build

```
vue init simulatedgreg/electron-vue my-project
cd my-project
npm install
npm install --save electron-json-storage
```
Now edit `app/src/renderer/main.js` and include `electron-json-storage`:

    import * as storage from 'electron-json-storage'

Finally, make the production build:

    npm run build:darwin

**Comment by jviotti** [comment]
Thanks a lot for the details. I'm trying @metachris steps as I write.

> so it's a change that happened between 3.0.0 and 3.0.1.

There are only two commits between those versions:

- https://github.com/jviotti/electron-json-storage/commit/b9feeb1ad4f2aaed1a486a1f2d9acf64f78eb4e7
- https://github.com/jviotti/electron-json-storage/commit/e062878f29f9309d9250c7e30ec76c1330d3a7b2

The first commit has some backward compatible dependency upgrades. One of them, `exists-file`, was upgraded from v2 to v3, which might explain the reason.

Lets see how it goes over here...

**Comment by jviotti** [comment]
I'm getting a slightly different issue here (in macOS as well):

```
ERROR in renderer.js from UglifyJs
Unexpected character '`' [renderer.js:20045,34]

ERROR in renderer.js from UglifyJs
Unexpected character '`' [renderer.js:20045,34]
```

I also get the same issue on 3.0.0.

**Comment by jviotti** [comment]
Oh, I think I found the problem. It looks like UglifyJS is getting confused about the ES6 features that we use in this module, like ``` and `=>`.

**Comment by jviotti** [comment]
I'm a webpack noob, so I honestly have no clue how to configure it correctly to make it understand ES6. In the mid-time, I'm happy to get rid of the ES6 features we're using here (which are very few).

**Comment by jviotti** [comment]
Hm, now I'm getting the originally reported error:

```
ERROR in renderer.js from UglifyJs
Unexpected token: name (args) [renderer.js:26286,6]

ERROR in renderer.js from UglifyJs
Unexpected token: name (args) [renderer.js:26286,6]
```

**Comment by jviotti** [comment]
OK, looks like the issue comes from `exists-file`, which requires `cb2promise`, which causes problems because of this line: https://github.com/Kikobeats/cb2promise/blob/master/index.js#L7.

I'll replace this dependency with some custom code in `electron-json-storage` and that should be it.

**Comment by jviotti** [comment]
@metachris @tvanro Check 3.0.4. Everything seems to work fine now! 

Still, in order to avoid similar issues in the future, I'd recommend opening a ticket on the `vue-cli` so they make sure ES6 dependencies get transpiled before running UglifyJS on them.

**Comment by metachris** [comment]
Awesome! :+1:

**Comment by Sobient** [comment]
Had some code that threw this issue:

```
  return function () {
    clearTimeout(timeoutID)
    let args = arguments
    let that = this
    timeoutID = setTimeout(function () {
      fn.apply(that, args)
    }, delay)
  }

The problem was that uglify doesn't understand ES6, so changing **let** to **var** fixed the problem.
```

**Comment by jviotti** [comment]
You should use [`uglify-es`](https://www.npmjs.com/package/uglify-es) if you need to deal with ES6 code.
