### ISSUE TITLE
fs.existsSync is not a function

### ISSUE THREAD

**Issue by gizburdt** [jviotti/electron-json-storage#61]
Hi,

When using the plugin I get this console error: `fs.existsSync is not a function`. Also get this error while compiling code with Webpack: `Error: Can't resolve 'fs' in '/Users/Gijs/Server/anvil/node_modules/electron-json-storage/lib`. 

Am I doing something wrong?

**Comment by jviotti** [comment]
Looks like a Webpack configuration issue. `fs` is a node built-in module. Maybe `target: 'node'` helps?
