### ISSUE TITLE
Build fails on import utils.js with Spectron

### ISSUE THREAD

**Issue by dok** [jviotti/electron-json-storage#62]
Looks like my Spectron tests are failing due to this line of code on this [line](https://github.com/jviotti/electron-json-storage/blob/master/lib/utils.js#L30):

```js
const app = electron.app || electron.remote.app;
```

I'm going to propose moving that line into the only place that it is used, with a conditional that it will use a default location if app does not exist. So [getUserDataPath](https://github.com/jviotti/electron-json-storage/blob/master/lib/utils.js#L42) will look like this:

```js
exports.getUserDataPath = function() {
  const app = electron.app || (electron.remote && electron.remote.app);
  if(app) {
    return path.join(app.getPath('userData'), 'storage');
  } else {
    return '/tmp/storage';
  }
};
``` 

This is not a breaking change. 

@jviotti

**Comment by jviotti** [comment]
Hey there, thanks for the heads up, I'm happy with that change. Are you sending a PR for it yourself?
