### ISSUE TITLE
get(key, callback)

### ISSUE THREAD

**Issue by shaneing** [jviotti/electron-json-storage#65]
```
getData(key) {
  let d;
  this.storage.get(key, (error, data) => {
    if (error) {
      err(`AutoComplete::getData(key) - Error for getting ${key}`);
    }
    d = data;
  });
  return d;
}
```

the content of storage file:

```
{}
```

But, an error occurred

**Comment by jviotti** [comment]
I believe you figured it out already, but `.get()` is an async function, and therefore your `getData` function will return before that completes.
